name: Deploy Load Balanced App

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. কোড ডাউনলোড করা
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. ডকার ইমেজ বিল্ড করা
      - name: Build Docker Image
        run: docker build -t devopscode24/url-shortener:latest .

      # 3. ডকার হাবে লগইন করা
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. ডকার হাবে পুশ করা
      - name: Push to Docker Hub
        run: docker push devopscode24/url-shortener:latest

      # 5. সার্ভার ১ এ ডিপ্লয় করা
      - name: Deploy to Server 1
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST_1 }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo docker pull devopscode24/url-shortener:latest
            sudo docker stop my-url-app || true
            sudo docker rm my-url-app || true
            sudo docker run -d -p 3000:3000 --name my-url-app devopscode24/url-shortener:latest

      # 6. সার্ভার ২ এ ডিপ্লয় করা
      - name: Deploy to Server 2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST_2 }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo docker pull devopscode24/url-shortener:latest
            sudo docker stop my-url-app || true
            sudo docker rm my-url-app || true
            sudo docker run -d -p 3000:3000 --name my-url-app devopscode24/url-shortener:latest
